// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4vHtPtRS8dckbcBE7nW2BsGu6DL7SVf8',
    appId: '1:558205228069:web:fca8829eebd1560caedbcc',
    messagingSenderId: '558205228069',
    projectId: 'makani-ecb0a',
    authDomain: 'makani-ecb0a.firebaseapp.com',
    storageBucket: 'makani-ecb0a.firebasestorage.app',
    measurementId: 'G-EP4DKWGRTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-sRiRU_cULiOzw1Jsmib6WcsvGU0SL-A',
    appId: '1:558205228069:android:8b09c5bdeca6599aaedbcc',
    messagingSenderId: '558205228069',
    projectId: 'makani-ecb0a',
    storageBucket: 'makani-ecb0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfK2MvQW23e0jcCbPuuxkpnP6jaylikR8',
    appId: '1:558205228069:ios:aacbd78941a04c9eaedbcc',
    messagingSenderId: '558205228069',
    projectId: 'makani-ecb0a',
    storageBucket: 'makani-ecb0a.firebasestorage.app',
    iosBundleId: 'com.example.makani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfK2MvQW23e0jcCbPuuxkpnP6jaylikR8',
    appId: '1:558205228069:ios:aacbd78941a04c9eaedbcc',
    messagingSenderId: '558205228069',
    projectId: 'makani-ecb0a',
    storageBucket: 'makani-ecb0a.firebasestorage.app',
    iosBundleId: 'com.example.makani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4vHtPtRS8dckbcBE7nW2BsGu6DL7SVf8',
    appId: '1:558205228069:web:2511d427c9f2baeeaedbcc',
    messagingSenderId: '558205228069',
    projectId: 'makani-ecb0a',
    authDomain: 'makani-ecb0a.firebaseapp.com',
    storageBucket: 'makani-ecb0a.firebasestorage.app',
    measurementId: 'G-J8TQGX00MM',
  );
}
